// src/app/AppRouter.tsx
import {
  Outlet,
  RouterProvider,
  ReactRouter,
  Route,
  RootRoute,
} from "@tanstack/react-router";
import { GamePage } from "./pages/game";
import { HomePage } from "./pages/home";

const rootRoute = new RootRoute({
  component: () => <Outlet />,
});

const homeRoute = new Route({
  getParentRoute: () => rootRoute,
  path: "/",
  component: HomePage,
});

const gameRoute = new Route({
  getParentRoute: () => rootRoute,
  path: "/game",
  component: GamePage,
});

const routeTree = rootRoute.addChildren([homeRoute, gameRoute]);

const router = new ReactRouter({ routeTree });

export function AppRouter() {
  return <RouterProvider router={router} />;
}

// Solid/src/app/AppRouter.tsx
import { lazy } from "solid-js";
import { Router, Routes, Route } from "@solidjs/router";
const HomePage = lazy(() => import("./pages/home/HomePage"));
const GamePage = lazy(() => import("./pages/game/GamePage"));

export function AppRouter() {
    return (
        <Router>
            <Routes>
                <Route path="/" component={HomePage} />
                <Route path="/game" component={GamePage} />
            </Routes>
        </Router>
    );
};
